#!/usr/bin/env bash
#Loops from 1 and 10 and displays bad luck on the 4th iteration, displays good luck on the 8th iteration and 
#displays Best School for other iterations

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
	echo "bad luck"
	elif [ $i -eq 7 ]
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	(( i++ ))
done
