#!/usr/bin/env bash
#Bash script that displays the content of the current directory
#In a list format where only the part of the name after the dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
